name: Update README

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run README update script
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: node ./scripts/update-readme/index.js
